services:
  bot:
    image: dms:latest
    container_name: discord-message-scheduler
    env_file: .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    network_mode: "host"
    volumes: data:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"